management:
  endpoints:
    web:
      exposure:
        include: bus-refresh, bus-env, event

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true
    bus:
      trace:
        enabled: true
