management:
  endpoints:
    web:
      exposure:
        include: bus-refresh, bus-env,env


spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true
  application:
    name: cloud-bus-kafka2


server:
  port: 9001
